from __future__ import annotations

from dataclasses import dataclass
import json
import logging
from pathlib import Path
import re

logger = logging.getLogger("bnt.catalog")

# Pre-compiled regexes for normalize_key (hot path)
_RE_NON_ALNUM = re.compile(r"[^a-z0-9]+")
_RE_MULTI_SPACE = re.compile(r"\s+")


@dataclass(frozen=True)
class BiomarkerDefinition:
    biomarker_id: str
    canonical_name: str
    loinc: str
    normalized_unit: str
    allowed_specimens: frozenset[str]
    aliases: tuple[str, ...]


def normalize_key(value: str) -> str:
    lowered = value.strip().lower()
    lowered = _RE_NON_ALNUM.sub(" ", lowered)
    return _RE_MULTI_SPACE.sub(" ", lowered).strip()


def normalize_specimen(specimen: str | None) -> str | None:
    """Normalize specimen type to canonical form (serum, plasma, whole_blood, urine).

    Unknown specimens (e.g., "CSF", "ascites") are returned as-is (lowercased).
    This causes them to fail specimen filtering in the normalizer, producing
    status="review_needed" with reason="no_candidate_for_specimen". This is the
    intended fail-closed behavior for non-blood/non-urine specimens.
    """
    if specimen is None:
        return None

    specimen_key = normalize_key(specimen)
    mapping = {
        "serum": "serum",
        "plasma": "plasma",
        "serum plasma": "serum",
        "ser plas": "serum",
        "ser plasma": "serum",
        "serum plas": "serum",
        "whole blood": "whole_blood",
        "blood": "whole_blood",
        "bld": "whole_blood",
        "wb": "whole_blood",
        "venous blood": "whole_blood",
        "arterial blood": "whole_blood",
        "capillary blood": "whole_blood",
        "mixed venous blood": "whole_blood",
        "cord blood": "whole_blood",
        "urine": "urine",
        "random urine": "urine",
        "spot urine": "urine",
        "24h urine": "urine",
        "24 hour urine": "urine",
        "timed urine": "urine",
    }
    return mapping.get(specimen_key, specimen_key or None)


_BLOOD = frozenset({"serum", "plasma", "whole_blood"})
_WHOLE_BLOOD = frozenset({"whole_blood"})
_URINE = frozenset({"urine"})

BIOMARKER_CATALOG: dict[str, BiomarkerDefinition] = {
    "glucose_serum": BiomarkerDefinition(
        biomarker_id="glucose_serum",
        canonical_name="Glucose",
        loinc="2345-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=(
            "Glucose",
            "Glucose, Serum",
            "Glucose, Plasma",
            "Serum Glucose",
            "Blood Glucose",
            "GLU",
            "FBS",
            "Fasting Glucose",
            "Fasting Blood Sugar",
            "Glucose SerPl",
            "Glucose [Mass/volume] in Blood",
            "Glucose [Mass/volume] in Serum or Plasma",
            "Glucose [Moles/volume] in Blood",
            "Glucose [Moles/volume] in Serum or Plasma",
            "Glucose, Fasting",
            "Bedside Glucose",
            "Random Glucose",
        ),
    ),
    "glucose_urine": BiomarkerDefinition(
        biomarker_id="glucose_urine",
        canonical_name="Urine Glucose",
        loinc="53328-1",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Glucose", "Urine Glucose", "GLU",
                 "Glucose [Mass/volume] in Urine by Test strip"),
    ),
    "hba1c": BiomarkerDefinition(
        biomarker_id="hba1c",
        canonical_name="Hemoglobin A1c",
        loinc="4548-4",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=(
            "Hemoglobin A1c",
            "A1C",
            "HbA1c",
            "Glycated Hemoglobin",
            "Glycated Hb",
            "GlycoHb",
            "Hgb A1C",
            "Glycohemoglobin A1C",
            "Hemoglobin A1c/Hemoglobin.total in Blood",
            "Hemoglobin A1c/Hemoglobin.total in Blood by IFCC protocol",
        ),
    ),
    "total_cholesterol": BiomarkerDefinition(
        biomarker_id="total_cholesterol",
        canonical_name="Total Cholesterol",
        loinc="2093-3",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Total Cholesterol", "Cholesterol", "Cholesterol, Total", "CHOL TOTAL",
                 "Chol", "TCHOL", "TC",
                 "Cholesterol [Mass/volume] in Serum or Plasma"),
    ),
    "ldl_cholesterol": BiomarkerDefinition(
        biomarker_id="ldl_cholesterol",
        canonical_name="LDL Cholesterol",
        loinc="2089-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("LDL Cholesterol", "LDL-C", "LDL", "LDL Chol Calc", "LDL Cholesterol Calc", "LDL Cholesterol Calculated", "LDL Calc",
                 "Cholesterol, LDL, Calculated",
                 "Low Density Lipoprotein Cholesterol", "LDL Chol Calc (NIH)",
                 "Cholesterol in LDL [Mass/volume] in Serum or Plasma",
                 "Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay",
                 "Cholesterol in LDL [Mass/volume] in Serum or Plasma by calculation"),
    ),
    "hdl_cholesterol": BiomarkerDefinition(
        biomarker_id="hdl_cholesterol",
        canonical_name="HDL Cholesterol",
        loinc="2085-9",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("HDL Cholesterol", "HDL-C", "HDL", "HDL Chol", "HDL Cholesterol Direct",
                 "Cholesterol, HDL",
                 "High Density Lipoprotein Cholesterol",
                 "Cholesterol in HDL [Mass/volume] in Serum or Plasma"),
    ),
    "triglycerides": BiomarkerDefinition(
        biomarker_id="triglycerides",
        canonical_name="Triglycerides",
        loinc="2571-8",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Triglycerides", "Triglyceride", "TG", "TRIG", "Triglyc",
                 "Triglycerides [Mass/volume] in Serum or Plasma",
                 "Triglyceride [Mass/volume] in Serum or Plasma"),
    ),
    "creatinine": BiomarkerDefinition(
        biomarker_id="creatinine",
        canonical_name="Creatinine",
        loinc="2160-0",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Creatinine", "Creatinine, Serum", "Creatinine, Plasma", "Creat", "Crea", "SCr",
                 "Serum Creatinine", "Creatinine SerPl",
                 "Creatinine [Mass/volume] in Blood", "Creatinine [Mass/volume] in Serum or Plasma"),
    ),
    "creatinine_urine": BiomarkerDefinition(
        biomarker_id="creatinine_urine",
        canonical_name="Urine Creatinine",
        loinc="2161-8",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Creatinine", "Urine Creatinine", "Urinary Creatinine", "Creat", "Crea", "Creatinine, Urine"),
    ),
    # --- Wave 2: Liver panel ---
    "alt": BiomarkerDefinition(
        biomarker_id="alt",
        canonical_name="ALT",
        loinc="1742-6",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("ALT", "SGPT", "Alanine Aminotransferase", "ALT/SGPT",
                 "Alanine Aminotransferase (ALT)",
                 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "ast": BiomarkerDefinition(
        biomarker_id="ast",
        canonical_name="AST",
        loinc="1920-8",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("AST", "SGOT", "Aspartate Aminotransferase", "AST/SGOT",
                 "Asparate Aminotransferase (AST)",
                 "Aspartate aminotransferase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "alp": BiomarkerDefinition(
        biomarker_id="alp",
        canonical_name="Alkaline Phosphatase",
        loinc="6768-6",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("ALP", "Alk Phos", "Alkaline Phosphatase", "Alkaline Phosph", "Alkaline Phos.",
                 "Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "total_bilirubin": BiomarkerDefinition(
        biomarker_id="total_bilirubin",
        canonical_name="Total Bilirubin",
        loinc="1975-2",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Total Bilirubin", "Bilirubin", "TBIL", "Bili", "T Bili", "Bilirubin Total",
                 "Bilirubin.total [Mass/volume] in Blood",
                 "Bilirubin.total [Mass/volume] in Serum or Plasma"),
    ),
    "albumin": BiomarkerDefinition(
        biomarker_id="albumin",
        canonical_name="Albumin",
        loinc="1863-0",
        normalized_unit="g/dL",
        allowed_specimens=_BLOOD,
        aliases=("Albumin", "Alb", "Serum Albumin", "Albumin, Blood",
                 "Albumin, Serum",
                 "Albumin [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 2: Thyroid ---
    "tsh": BiomarkerDefinition(
        biomarker_id="tsh",
        canonical_name="TSH",
        loinc="3016-3",
        normalized_unit="mIU/L",
        allowed_specimens=_BLOOD,
        aliases=("TSH", "Thyroid Stimulating Hormone", "Thyrotropin",
                 "TSH, 3rd Generation", "TSH, Ultrasensitive",
                 "Thyrotropin [Units/volume] in Serum or Plasma"),
    ),
    "free_t4": BiomarkerDefinition(
        biomarker_id="free_t4",
        canonical_name="Free T4",
        loinc="3024-7",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Free T4", "FT4", "Thyroxine Free", "Free Thyroxine",
                 "Thyroxine (T4), Free", "T4, Free", "Thyroxine, Free (FT4)",
                 "Thyroxine (T4) free [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 2: Renal expansion ---
    "bun": BiomarkerDefinition(
        biomarker_id="bun",
        canonical_name="BUN",
        loinc="3094-0",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("BUN", "Urea Nitrogen", "Blood Urea Nitrogen", "Urea", "Urea N",
                 "Urea nitrogen [Mass/volume] in Blood", "Urea nitrogen [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 2: Inflammation ---
    "hscrp": BiomarkerDefinition(
        biomarker_id="hscrp",
        canonical_name="hs-CRP",
        loinc="30522-7",
        normalized_unit="mg/L",
        allowed_specimens=_BLOOD,
        aliases=("hs-CRP", "hsCRP", "High Sensitivity CRP", "High Sensitivity C-Reactive Protein",
                 "C-Reactive Protein, High Sensitivity",
                 "C-Reactive Protein, Cardiac", "C-Reactive Protein, Quant"),
    ),
    "crp": BiomarkerDefinition(
        biomarker_id="crp",
        canonical_name="CRP",
        loinc="1988-5",
        normalized_unit="mg/L",
        allowed_specimens=_BLOOD,
        aliases=("CRP", "C-Reactive Protein",
                 "C reactive protein [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 2: CBC ---
    "wbc": BiomarkerDefinition(
        biomarker_id="wbc",
        canonical_name="WBC",
        loinc="6690-2",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("WBC", "White Blood Cells", "Leukocytes", "White Cell Count",
                 "WBC Count", "Leukocyte Count", "White Blood Cell Count", "WBC x 1000",
                 "Leukocytes [#/volume] in Blood",
                 "Leukocytes [#/volume] in Blood by Automated count"),
    ),
    "hemoglobin": BiomarkerDefinition(
        biomarker_id="hemoglobin",
        canonical_name="Hemoglobin",
        loinc="718-7",
        normalized_unit="g/dL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Hemoglobin", "Hgb", "Hb", "Haemoglobin",
                 "Hemoglobin [Mass/volume]", "Hemoglobin [Mass/volume] in Blood"),
    ),
    "hematocrit": BiomarkerDefinition(
        biomarker_id="hematocrit",
        canonical_name="Hematocrit",
        loinc="4544-3",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Hematocrit", "Hct", "PCV", "Packed Cell Volume",
                 "Hematocrit, Calculated",
                 "Hematocrit [Volume Fraction] of Blood",
                 "Hematocrit [Volume Fraction] of Blood by Automated count",
                 "Hematocrit [Volume Fraction] of Blood by calculation"),
    ),
    "platelets": BiomarkerDefinition(
        biomarker_id="platelets",
        canonical_name="Platelets",
        loinc="777-3",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Platelets", "PLT", "Platelet Count", "Thrombocytes", "Plt Count",
                 "Platelets x 1000",
                 "Platelets [#/volume] in Blood",
                 "Platelets [#/volume] in Blood by Automated count"),
    ),
    # --- Wave 3: Vitamins ---
    "vitamin_d": BiomarkerDefinition(
        biomarker_id="vitamin_d",
        canonical_name="Vitamin D 25-OH",
        loinc="14979-9",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Vitamin D", "25-OH Vitamin D", "25-Hydroxyvitamin D", "Vit D", "D 25-OH",
                 "Vitamin D, 25-OH", "25-OH-D", "25OH Vitamin D", "Vitamin D 25-Hydroxy",
                 "Vitamin D,25-OH,Total"),
    ),
    "vitamin_b12": BiomarkerDefinition(
        biomarker_id="vitamin_b12",
        canonical_name="Vitamin B12",
        loinc="2132-9",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Vitamin B12", "B12", "Cobalamin", "Vitamin B-12", "Cyanocobalamin"),
    ),
    "folate": BiomarkerDefinition(
        biomarker_id="folate",
        canonical_name="Folate",
        loinc="2155-0",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Folate", "Folic Acid", "Vitamin B9", "Folate (Folic Acid), Serum"),
    ),
    # --- Wave 3: Minerals ---
    "iron": BiomarkerDefinition(
        biomarker_id="iron",
        canonical_name="Iron",
        loinc="2498-4",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Iron", "Serum Iron", "Fe", "Iron, Total", "Total Iron",
                 "Iron [Mass/volume] in Serum or Plasma"),
    ),
    "ferritin": BiomarkerDefinition(
        biomarker_id="ferritin",
        canonical_name="Ferritin",
        loinc="2276-4",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Ferritin", "Serum Ferritin", "Ferritin, Serum",
                 "Ferritin [Mass/volume] in Serum or Plasma"),
    ),
    "magnesium": BiomarkerDefinition(
        biomarker_id="magnesium",
        canonical_name="Magnesium",
        loinc="19123-9",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Magnesium", "Mag", "Mg", "Serum Magnesium",
                 "Magnesium, Serum",
                 "Magnesium [Mass/volume] in Serum or Plasma",
                 "Magnesium [Mass/volume] in Blood"),
    ),
    # --- Wave 4: CBC sub-components ---
    "rbc": BiomarkerDefinition(
        biomarker_id="rbc",
        canonical_name="Red Blood Cells",
        loinc="789-8",
        normalized_unit="M/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Red Blood Cells", "RBC", "RBC Count", "Erythrocytes",
                 "Erythrocyte Count",
                 "Erythrocytes [#/volume] in Blood",
                 "Erythrocytes [#/volume] in Blood by Automated count"),
    ),
    "mcv": BiomarkerDefinition(
        biomarker_id="mcv",
        canonical_name="MCV",
        loinc="787-2",
        normalized_unit="fL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("MCV", "Mean Corpuscular Volume",
                 "MCV [Entitic volume]",
                 "MCV [Entitic mean volume] in Red Blood Cells",
                 "MCV [Entitic mean volume] in Red Blood Cells by Automated count",
                 "MCV [Entitic volume] by Automated count"),
    ),
    "mch": BiomarkerDefinition(
        biomarker_id="mch",
        canonical_name="MCH",
        loinc="785-6",
        normalized_unit="pg",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("MCH", "Mean Corpuscular Hemoglobin",
                 "MCH [Entitic mass]",
                 "MCH [Entitic mass] by Automated count"),
    ),
    "mchc": BiomarkerDefinition(
        biomarker_id="mchc",
        canonical_name="MCHC",
        loinc="786-4",
        normalized_unit="g/dL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("MCHC", "Mean Corpuscular Hemoglobin Concentration",
                 "MCHC [Mass/volume]",
                 "MCHC [Entitic Mass/volume] in Red Blood Cells by Automated count",
                 "MCHC [Mass/volume] by Automated count"),
    ),
    "rdw": BiomarkerDefinition(
        biomarker_id="rdw",
        canonical_name="RDW",
        loinc="788-0",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("RDW", "Red Cell Distribution Width", "RDW-CV",
                 "Erythrocyte distribution width [Ratio] by Automated count",
                 "Erythrocyte [DistWidth] in Blood",
                 "Erythrocyte [DistWidth] in Blood by Automated count"),
    ),
    "rdw_sd": BiomarkerDefinition(
        biomarker_id="rdw_sd",
        canonical_name="RDW-SD",
        loinc="21000-5",
        normalized_unit="fL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("RDW-SD", "RDW Standard Deviation",
                 "Erythrocyte distribution width [Entitic volume] in Blood by Automated count"),
    ),
    "mpv": BiomarkerDefinition(
        biomarker_id="mpv",
        canonical_name="MPV",
        loinc="32623-1",
        normalized_unit="fL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("MPV", "Mean Platelet Volume",
                 "Platelet [Entitic mean volume] in Blood by Automated count"),
    ),
    "pdw": BiomarkerDefinition(
        biomarker_id="pdw",
        canonical_name="PDW",
        loinc="32207-3",
        normalized_unit="fL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("PDW", "Platelet Distribution Width",
                 "Platelet distribution width [Entitic volume] in Blood by Automated count"),
    ),
    # --- Wave 4: Coagulation ---
    "pt": BiomarkerDefinition(
        biomarker_id="pt",
        canonical_name="Prothrombin Time",
        loinc="5902-2",
        normalized_unit="sec",
        allowed_specimens=_BLOOD,
        aliases=("PT", "Prothrombin Time", "Pro Time", "Prothrombin time (PT)"),
    ),
    "inr": BiomarkerDefinition(
        biomarker_id="inr",
        canonical_name="INR",
        loinc="6301-6",
        normalized_unit="ratio",
        allowed_specimens=_BLOOD,
        aliases=("INR", "INR(PT)", "PT - INR", "International Normalized Ratio",
                 "INR in Platelet poor plasma by Coagulation assay"),
    ),
    "ptt": BiomarkerDefinition(
        biomarker_id="ptt",
        canonical_name="PTT",
        loinc="3173-2",
        normalized_unit="sec",
        allowed_specimens=_BLOOD,
        aliases=("PTT", "aPTT", "Partial Thromboplastin Time",
                 "Activated Partial Thromboplastin Time",
                 "aPTT in Blood by Coagulation assay"),
    ),
    # --- Wave 4: Other high-frequency ---
    "anion_gap": BiomarkerDefinition(
        biomarker_id="anion_gap",
        canonical_name="Anion Gap",
        loinc="33037-3",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Anion Gap", "AG",
                 "Anion gap in Serum or Plasma",
                 "Anion gap in Serum or Plasma by calculation"),
    ),
    "lactate": BiomarkerDefinition(
        biomarker_id="lactate",
        canonical_name="Lactate",
        loinc="2524-7",
        normalized_unit="mmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Lactate", "Lactic Acid", "Lactate [Moles/volume] in Blood"),
    ),
    # --- Wave 4: Electrolytes (from MIMIC/Synthea analysis) ---
    "sodium": BiomarkerDefinition(
        biomarker_id="sodium",
        canonical_name="Sodium",
        loinc="2951-2",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Sodium", "Na", "Serum Sodium", "Sodium, Whole Blood",
                 "Sodium [Moles/volume] in Blood",
                 "Sodium [Moles/volume] in Serum or Plasma"),
    ),
    "potassium": BiomarkerDefinition(
        biomarker_id="potassium",
        canonical_name="Potassium",
        loinc="2823-3",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Potassium", "K", "Serum Potassium", "Potassium Level", "Potassium, Whole Blood",
                 "Potassium [Moles/volume] in Blood",
                 "Potassium [Moles/volume] in Serum or Plasma"),
    ),
    "chloride": BiomarkerDefinition(
        biomarker_id="chloride",
        canonical_name="Chloride",
        loinc="2075-0",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Chloride", "Cl", "Serum Chloride", "Chloride, Whole Blood",
                 "Chloride [Moles/volume] in Blood",
                 "Chloride [Moles/volume] in Serum or Plasma"),
    ),
    "bicarbonate": BiomarkerDefinition(
        biomarker_id="bicarbonate",
        canonical_name="Bicarbonate",
        loinc="1963-8",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Bicarbonate", "CO2", "Total CO2", "Carbon Dioxide", "HCO3",
                 "Calculated Total CO2", "Calculated Bicarbonate", "Bicarb",
                 "Bicarbonate [Moles/volume] in Arterial blood",
                 "Bicarbonate [Moles/volume] in Venous blood",
                 "Carbon dioxide total [Moles/volume] in Blood",
                 "Carbon dioxide  total [Moles/volume] in Serum or Plasma",
                 "Carbon dioxide  total [Moles/volume] in Venous blood",
                 "Bicarbonate [Moles/volume] in Serum or Plasma"),
    ),
    "calcium": BiomarkerDefinition(
        biomarker_id="calcium",
        canonical_name="Calcium",
        loinc="17861-6",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Calcium", "Ca", "Calcium, Total", "Serum Calcium", "Total Calcium",
                 "Calcium, Serum",
                 "Calcium [Mass/volume] in Blood", "Calcium [Mass/volume] in Serum or Plasma"),
    ),
    "phosphate": BiomarkerDefinition(
        biomarker_id="phosphate",
        canonical_name="Phosphate",
        loinc="2777-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Phosphate", "Phosphorus", "Phos", "Inorganic Phosphate",
                 "Phosphate [Mass/volume] in Serum or Plasma"),
    ),
    "uric_acid": BiomarkerDefinition(
        biomarker_id="uric_acid",
        canonical_name="Uric Acid",
        loinc="3084-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Uric Acid", "Urate", "Uric Acid, Serum",
                 "Urate [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 6: Enzymes ---
    "ldh": BiomarkerDefinition(
        biomarker_id="ldh",
        canonical_name="Lactate Dehydrogenase",
        loinc="2532-0",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("LDH", "Lactate Dehydrogenase", "Lactate Dehydrogenase (LD)", "LD",
                 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma",
                 "Lactate dehydrogenase [Enzymatic activity/volume] in Serum or Plasma by Lactate to pyruvate reaction"),
    ),
    "lipase": BiomarkerDefinition(
        biomarker_id="lipase",
        canonical_name="Lipase",
        loinc="3040-3",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("Lipase", "Serum Lipase", "Lipase, Serum",
                 "Lipase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "ck": BiomarkerDefinition(
        biomarker_id="ck",
        canonical_name="Creatine Kinase",
        loinc="2157-6",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("CK", "Creatine Kinase", "Creatine Kinase (CK)", "CPK", "CK Total",
                 "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "ck_mb": BiomarkerDefinition(
        biomarker_id="ck_mb",
        canonical_name="CK-MB",
        loinc="2154-3",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("CK-MB", "Creatine Kinase, MB Isoenzyme", "CKMB", "CPK-MB"),
    ),
    "ck_mb_index": BiomarkerDefinition(
        biomarker_id="ck_mb_index",
        canonical_name="CK-MB Index",
        loinc="12189-7",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("CK-MB Index", "CKMB Index", "CPK-MB INDEX",
                 "Creatine kinase.MB/Creatine kinase.total [Pure catalytic fraction] in Serum or Plasma by Calculation"),
    ),
    # --- Wave 6: Cardiac ---
    "troponin_t": BiomarkerDefinition(
        biomarker_id="troponin_t",
        canonical_name="Troponin T",
        loinc="6598-7",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Troponin T", "cTnT", "Cardiac Troponin T"),
    ),
    "vancomycin": BiomarkerDefinition(
        biomarker_id="vancomycin",
        canonical_name="Vancomycin",
        loinc="20578-1",
        normalized_unit="ug/mL",
        allowed_specimens=_BLOOD,
        aliases=("Vancomycin", "Vancomycin Random",
                 "Vancomycin [Mass/volume] in Serum or Plasma --random"),
    ),
    "vancomycin_trough": BiomarkerDefinition(
        biomarker_id="vancomycin_trough",
        canonical_name="Vancomycin Trough",
        loinc="4092-3",
        normalized_unit="ug/mL",
        allowed_specimens=_BLOOD,
        aliases=("Vancomycin Trough", "Vanc Trough",
                 "Vancomycin [Mass/volume] in Serum or Plasma --trough"),
    ),
    "digoxin": BiomarkerDefinition(
        biomarker_id="digoxin",
        canonical_name="Digoxin",
        loinc="10535-3",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Digoxin", "Digoxin Level", "Lanoxin",
                 "Digoxin [Mass/volume] in Serum or Plasma"),
    ),
    "tacrolimus": BiomarkerDefinition(
        biomarker_id="tacrolimus",
        canonical_name="Tacrolimus",
        loinc="11253-2",
        normalized_unit="ng/mL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Tacrolimus", "Tacrolimus-FK506", "FK506",
                 "Tacrolimus [Mass/volume] in Blood"),
    ),
    "salicylates": BiomarkerDefinition(
        biomarker_id="salicylates",
        canonical_name="Salicylates",
        loinc="4024-6",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Salicylates", "Salicylate", "Salicylate Level",
                 "Salicylates [Mass/volume] in Serum or Plasma"),
    ),
    "myoglobin": BiomarkerDefinition(
        biomarker_id="myoglobin",
        canonical_name="Myoglobin",
        loinc="2639-3",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Myoglobin", "Serum Myoglobin", "Myoglobin Level",
                 "Myoglobin [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 6: Blood gases ---
    "pco2": BiomarkerDefinition(
        biomarker_id="pco2",
        canonical_name="pCO2",
        loinc="2019-8",
        normalized_unit="mmHg",
        allowed_specimens=_BLOOD,
        aliases=("pCO2", "paCO2", "Carbon Dioxide Partial Pressure",
                 "Carbon dioxide [Partial pressure] in Arterial blood",
                 "Carbon dioxide [Partial pressure] in Blood",
                 "Carbon dioxide [Partial pressure] in Venous blood"),
    ),
    "po2": BiomarkerDefinition(
        biomarker_id="po2",
        canonical_name="pO2",
        loinc="2703-7",
        normalized_unit="mmHg",
        allowed_specimens=_BLOOD,
        aliases=("pO2", "paO2", "Oxygen Partial Pressure",
                 "Oxygen [Partial pressure] in Arterial blood",
                 "Oxygen [Partial pressure] in Blood",
                 "Oxygen [Partial pressure] in Venous blood"),
    ),
    "base_excess": BiomarkerDefinition(
        biomarker_id="base_excess",
        canonical_name="Base Excess",
        loinc="11555-0",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Base Excess", "BE",
                 "Base excess in Blood by calculation"),
    ),
    "base_deficit": BiomarkerDefinition(
        biomarker_id="base_deficit",
        canonical_name="Base Deficit",
        loinc="30318-0",
        normalized_unit="mEq/L",
        allowed_specimens=_BLOOD,
        aliases=("Base Deficit", "BD",
                 "Base deficit in Blood"),
    ),
    # --- Wave 6: Other ---
    "globulin": BiomarkerDefinition(
        biomarker_id="globulin",
        canonical_name="Globulin",
        loinc="10834-0",
        normalized_unit="g/dL",
        allowed_specimens=_BLOOD,
        aliases=("Globulin", "Serum Globulin", "Total Globulin",
                 "Globulin [Mass/volume] in Serum by calculation"),
    ),
    "ionized_calcium": BiomarkerDefinition(
        biomarker_id="ionized_calcium",
        canonical_name="Ionized Calcium",
        loinc="1994-3",
        normalized_unit="mmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Ionized Calcium", "Free Calcium", "Calcium Ionized", "iCa"),
    ),
    "fibrinogen": BiomarkerDefinition(
        biomarker_id="fibrinogen",
        canonical_name="Fibrinogen",
        loinc="3255-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Fibrinogen", "Fibrinogen, Functional", "Fibrinogen Activity"),
    ),
    "eag": BiomarkerDefinition(
        biomarker_id="eag",
        canonical_name="Estimated Average Glucose",
        loinc="27353-2",
        normalized_unit="mg/dL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("eAG", "Estimated Average Glucose", "Estimated Avg Glucose"),
    ),
    "blood_ph": BiomarkerDefinition(
        biomarker_id="blood_ph",
        canonical_name="Blood pH",
        loinc="2744-1",
        normalized_unit="pH",
        allowed_specimens=_BLOOD,
        aliases=("pH", "Blood pH", "Arterial pH", "pH of Arterial blood",
                 "pH of Blood", "pH of Venous blood"),
    ),
    "oxygen_saturation": BiomarkerDefinition(
        biomarker_id="oxygen_saturation",
        canonical_name="Oxygen Saturation",
        loinc="2708-6",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("Oxygen Saturation", "O2 Sat", "SpO2", "SaO2", "O2Sat"),
    ),
    "oxyhemoglobin": BiomarkerDefinition(
        biomarker_id="oxyhemoglobin",
        canonical_name="Oxyhemoglobin",
        loinc="11559-2",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("Oxyhemoglobin", "Oxyhemoglobin Percent", "O2Hb", "FO2Hb",
                 "Fractional oxyhemoglobin in Blood"),
    ),
    "carboxyhemoglobin": BiomarkerDefinition(
        biomarker_id="carboxyhemoglobin",
        canonical_name="Carboxyhemoglobin",
        loinc="20563-3",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("Carboxyhemoglobin", "Carboxyhemoglobin Percent", "COHb",
                 "Carboxyhemoglobin/Hemoglobin.total in Blood"),
    ),
    "methemoglobin": BiomarkerDefinition(
        biomarker_id="methemoglobin",
        canonical_name="Methemoglobin",
        loinc="2614-6",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("Methemoglobin", "Methemoglobin Percent", "MetHb", "MetHgb",
                 "Methemoglobin/Hemoglobin.total in Blood"),
    ),
    "oxygen_content": BiomarkerDefinition(
        biomarker_id="oxygen_content",
        canonical_name="Oxygen Content",
        loinc="57800-5",
        normalized_unit="mL/dL",
        allowed_specimens=_BLOOD,
        aliases=("O2 Content", "Oxygen Content", "ctO2",
                 "Oxygen content in Blood by calculation"),
    ),
    # --- Urinalysis ---
    "urine_specific_gravity": BiomarkerDefinition(
        biomarker_id="urine_specific_gravity",
        canonical_name="Urine Specific Gravity",
        loinc="5811-5",
        normalized_unit="",
        allowed_specimens=_URINE,
        aliases=("Specific Gravity", "Urine Specific Gravity", "Urinary Specific Gravity", "SG",
                 "Specific gravity of Urine by Test strip"),
    ),
    "urine_ph": BiomarkerDefinition(
        biomarker_id="urine_ph",
        canonical_name="Urine pH",
        loinc="5803-2",
        normalized_unit="pH",
        allowed_specimens=_URINE,
        aliases=("pH", "Urine pH",
                 "pH of Urine by Test strip"),
    ),
    "urine_protein": BiomarkerDefinition(
        biomarker_id="urine_protein",
        canonical_name="Urine Protein",
        loinc="2888-6",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Protein", "Urine Protein",
                 "Protein [Mass/volume] in Urine by Test strip"),
    ),
    "urine_ketones": BiomarkerDefinition(
        biomarker_id="urine_ketones",
        canonical_name="Urine Ketones",
        loinc="2514-8",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Ketones", "Ketone", "Urine Ketones",
                 "Ketones [Mass/volume] in Urine by Test strip"),
    ),
    "urine_bilirubin": BiomarkerDefinition(
        biomarker_id="urine_bilirubin",
        canonical_name="Urine Bilirubin",
        loinc="1977-8",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Bilirubin", "Urine Bilirubin",
                 "Bilirubin.total [Mass/volume] in Urine by Test strip"),
    ),
    # --- Wave 5: WBC differentials ---
    "neutrophils": BiomarkerDefinition(
        biomarker_id="neutrophils",
        canonical_name="Neutrophils",
        loinc="26499-4",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Neutrophils", "Neutrophil Count", "ANC", "Absolute Neutrophil Count",
                 "Absolute Neutrophils", "Polys", "Segs", "Seg", "PMN",
                 "Neutrophils (Absolute)",
                 "Neutrophils [#/volume] in Blood",
                 "Neutrophils [#/volume] in Blood by Automated count"),
    ),
    "lymphocytes": BiomarkerDefinition(
        biomarker_id="lymphocytes",
        canonical_name="Lymphocytes",
        loinc="26474-7",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Lymphocytes", "Lymphocyte Count", "Lymph", "Lymphs",
                 "Absolute Lymphocyte Count", "Absolute Lymphocytes",
                 "Lymphocytes (Absolute)",
                 "Lymphocytes [#/volume] in Blood",
                 "Lymphocytes [#/volume] in Blood by Automated count"),
    ),
    "monocytes": BiomarkerDefinition(
        biomarker_id="monocytes",
        canonical_name="Monocytes",
        loinc="26484-6",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Monocytes", "Monocyte Count", "Mono", "Monos",
                 "Absolute Monocyte Count", "Absolute Monocytes",
                 "Monocytes (Absolute)",
                 "Monocytes [#/volume] in Blood",
                 "Monocytes [#/volume] in Blood by Automated count"),
    ),
    "eosinophils": BiomarkerDefinition(
        biomarker_id="eosinophils",
        canonical_name="Eosinophils",
        loinc="26449-9",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Eosinophils", "Eosinophil Count", "Eos",
                 "Absolute Eosinophil Count", "Absolute Eosinophils",
                 "Eosinophils (Absolute)",
                 "Eosinophils [#/volume] in Blood",
                 "Eosinophils [#/volume] in Blood by Automated count"),
    ),
    "basophils": BiomarkerDefinition(
        biomarker_id="basophils",
        canonical_name="Basophils",
        loinc="26444-0",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Basophils", "Basophil Count", "Baso", "Basos",
                 "Absolute Basophil Count", "Absolute Basophils",
                 "Basophils (Absolute)",
                 "Basophils [#/volume] in Blood",
                 "Basophils [#/volume] in Blood by Automated count"),
    ),
    # --- Wave 5: WBC differential percentages ---
    "neutrophils_pct": BiomarkerDefinition(
        biomarker_id="neutrophils_pct",
        canonical_name="Neutrophils %",
        loinc="770-8",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Neutrophils Percent", "Neutrophil Percent", "Neut Pct",
                 "Neutrophils/100 leukocytes",
                 "Neutrophils/100 leukocytes in Blood",
                 "Neutrophils/100 leukocytes in Blood by Automated count",
                 "Neutrophils/Leukocytes in Blood by Automated count"),
    ),
    "lymphocytes_pct": BiomarkerDefinition(
        biomarker_id="lymphocytes_pct",
        canonical_name="Lymphocytes %",
        loinc="731-0",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Lymphocytes Percent", "Lymphocyte Percent", "Lymph Pct",
                 "Lymphocytes/100 leukocytes",
                 "Lymphocytes/100 leukocytes in Blood",
                 "Lymphocytes/100 leukocytes in Blood by Automated count",
                 "Lymphocytes/Leukocytes in Blood by Automated count"),
    ),
    "monocytes_pct": BiomarkerDefinition(
        biomarker_id="monocytes_pct",
        canonical_name="Monocytes %",
        loinc="742-7",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Monocytes Percent", "Monocyte Percent", "Mono Pct",
                 "Monocytes/100 leukocytes",
                 "Monocytes/100 leukocytes in Blood",
                 "Monocytes/100 leukocytes in Blood by Automated count",
                 "Monocytes/Leukocytes in Blood by Automated count"),
    ),
    "eosinophils_pct": BiomarkerDefinition(
        biomarker_id="eosinophils_pct",
        canonical_name="Eosinophils %",
        loinc="713-8",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Eosinophils Percent", "Eosinophil Percent", "Eos Pct",
                 "Eosinophils/100 leukocytes",
                 "Eosinophils/100 leukocytes in Blood",
                 "Eosinophils/100 leukocytes in Blood by Automated count",
                 "Eosinophils/Leukocytes in Blood by Automated count"),
    ),
    "basophils_pct": BiomarkerDefinition(
        biomarker_id="basophils_pct",
        canonical_name="Basophils %",
        loinc="704-7",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Basophils Percent", "Basophil Percent", "Baso Pct",
                 "Basophils/100 leukocytes",
                 "Basophils/100 leukocytes in Blood",
                 "Basophils/100 leukocytes in Blood by Automated count",
                 "Basophils/Leukocytes in Blood by Automated count"),
    ),
    "atypical_lymphocytes_pct": BiomarkerDefinition(
        biomarker_id="atypical_lymphocytes_pct",
        canonical_name="Atypical Lymphocytes %",
        loinc="13046-8",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Atypical Lymphocytes", "Atypical Lymphocytes Percent",
                 "Reactive Lymphocytes", "Reactive Lymphocytes Percent",
                 "Variant Lymphocytes", "Variant Lymphocytes Percent",
                 "Variant lymphocytes/100 leukocytes in Blood"),
    ),
    "metamyelocytes_pct": BiomarkerDefinition(
        biomarker_id="metamyelocytes_pct",
        canonical_name="Metamyelocytes %",
        loinc="28541-1",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Metamyelocytes", "Metamyelocytes Percent",
                 "Metamyelocytes/100 leukocytes in Blood"),
    ),
    "myelocytes_pct": BiomarkerDefinition(
        biomarker_id="myelocytes_pct",
        canonical_name="Myelocytes %",
        loinc="26498-6",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Myelocytes", "Myelocytes Percent",
                 "Myelocytes/100 leukocytes in Blood"),
    ),
    "blasts_pct": BiomarkerDefinition(
        biomarker_id="blasts_pct",
        canonical_name="Blasts %",
        loinc="26446-5",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Blasts", "Blasts Percent",
                 "Blasts/100 leukocytes in Blood"),
    ),
    # --- Wave 5: Other ---
    "total_protein": BiomarkerDefinition(
        biomarker_id="total_protein",
        canonical_name="Total Protein",
        loinc="2885-2",
        normalized_unit="g/dL",
        allowed_specimens=_BLOOD,
        aliases=("Total Protein", "Protein, Total", "Protein", "TP",
                 "Protein [Mass/volume] in Serum or Plasma"),
    ),
    "prealbumin": BiomarkerDefinition(
        biomarker_id="prealbumin",
        canonical_name="Prealbumin",
        loinc="14338-8",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Prealbumin", "Transthyretin", "Serum Prealbumin",
                 "Prealbumin [Mass/volume] in Serum or Plasma"),
    ),
    "egfr": BiomarkerDefinition(
        biomarker_id="egfr",
        canonical_name="eGFR",
        loinc="33914-3",
        normalized_unit="mL/min/1.73m2",
        allowed_specimens=_BLOOD,
        aliases=("eGFR", "GFR", "Estimated GFR", "Estimated Glomerular Filtration Rate",
                 "eGFR-MDRD", "eGFR-CKD-EPI",
                 "eGFR Non-Afr American", "eGFR African American", "GFR CKD-EPI",
                 "Glomerular filtration rate/1.73 sq M.predicted",
                 "Glomerular filtration rate [Volume Rate/Area] in Serum or Plasma by Creatinine-based formula (MDRD)/1.73 sq M"),
    ),
    # --- Wave 7: High-frequency clinical gaps ---
    "ggt": BiomarkerDefinition(
        biomarker_id="ggt",
        canonical_name="GGT",
        loinc="2324-2",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("GGT", "Gamma GT", "Gamma-Glutamyl Transferase", "Gamma Glutamyl Transpeptidase",
                 "Gamma Glutamyltransferase", "GGTP",
                 "Gamma glutamyl transferase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "amylase": BiomarkerDefinition(
        biomarker_id="amylase",
        canonical_name="Amylase",
        loinc="1798-8",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("Amylase", "Serum Amylase", "Amy",
                 "Amylase [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "direct_bilirubin": BiomarkerDefinition(
        biomarker_id="direct_bilirubin",
        canonical_name="Direct Bilirubin",
        loinc="1968-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Direct Bilirubin", "Bilirubin Direct", "Conjugated Bilirubin", "DBIL",
                 "Direct Bili",
                 "Bilirubin.direct [Mass/volume] in Serum or Plasma"),
    ),
    "troponin_i": BiomarkerDefinition(
        biomarker_id="troponin_i",
        canonical_name="Troponin I",
        loinc="10839-9",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Troponin I", "cTnI", "Cardiac Troponin I",
                 "Troponin I.cardiac [Mass/volume] in Serum or Plasma",
                 "Troponin I.cardiac [Mass/volume] in Serum or Plasma by High sensitivity method"),
    ),
    "bnp": BiomarkerDefinition(
        biomarker_id="bnp",
        canonical_name="BNP",
        loinc="42637-9",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("BNP", "Brain Natriuretic Peptide", "B-type Natriuretic Peptide",
                 "Natriuretic Peptide B",
                 "Natriuretic peptide B [Mass/volume] in Blood"),
    ),
    "nt_probnp": BiomarkerDefinition(
        biomarker_id="nt_probnp",
        canonical_name="NT-proBNP",
        loinc="33762-6",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("NT-proBNP", "NTproBNP", "Pro-BNP", "N-Terminal Pro-BNP",
                 "Natriuretic peptide.B prohormone N-Terminal [Mass/volume] in Serum or Plasma"),
    ),
    "d_dimer": BiomarkerDefinition(
        biomarker_id="d_dimer",
        canonical_name="D-Dimer",
        loinc="48065-7",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("D-Dimer", "DDimer", "Fibrin D-Dimer",
                 "Fibrin D-dimer FEU [Mass/volume] in Platelet poor plasma"),
    ),
    "reticulocytes": BiomarkerDefinition(
        biomarker_id="reticulocytes",
        canonical_name="Reticulocyte Count",
        loinc="17849-1",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Reticulocytes", "Reticulocyte Count", "Retic", "Retic Count",
                 "Reticulocyte Count, Automated",
                 "Reticulocytes/100 erythrocytes in Blood"),
    ),
    "procalcitonin": BiomarkerDefinition(
        biomarker_id="procalcitonin",
        canonical_name="Procalcitonin",
        loinc="33959-8",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Procalcitonin", "PCT", "Pro-Calcitonin",
                 "Procalcitonin [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 8: Longevity panel biomarkers ---
    "apob": BiomarkerDefinition(
        biomarker_id="apob",
        canonical_name="Apolipoprotein B",
        loinc="1884-6",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("ApoB", "Apolipoprotein B", "Apo B", "ApoB-100",
                 "Apolipoprotein B [Mass/volume] in Serum or Plasma"),
    ),
    "bun_creatinine_ratio": BiomarkerDefinition(
        biomarker_id="bun_creatinine_ratio",
        canonical_name="BUN/Creatinine Ratio",
        loinc="3097-3",
        normalized_unit="ratio",
        allowed_specimens=_BLOOD,
        aliases=("BUN/Creatinine Ratio", "BUN/Creat Ratio",
                 "Urea nitrogen/Creatinine [Mass Ratio] in Serum or Plasma"),
    ),
    "albumin_globulin_ratio": BiomarkerDefinition(
        biomarker_id="albumin_globulin_ratio",
        canonical_name="Albumin/Globulin Ratio",
        loinc="1759-0",
        normalized_unit="ratio",
        allowed_specimens=_BLOOD,
        aliases=("Albumin/Globulin Ratio", "A/G Ratio", "AG Ratio",
                 "Albumin/Globulin [Mass Ratio] in Serum or Plasma"),
    ),
    "dhea_s": BiomarkerDefinition(
        biomarker_id="dhea_s",
        canonical_name="DHEA-Sulfate",
        loinc="2191-5",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("DHEA-S", "DHEA-Sulfate", "Dehydroepiandrosterone Sulfate",
                 "DHEA-SO4", "Dehydroepiandrosterone (DHEA) Sulfate",
                 "Dehydroepiandrosterone sulfate (DHEA-S) [Mass/volume] in Serum or Plasma"),
    ),
    "estradiol": BiomarkerDefinition(
        biomarker_id="estradiol",
        canonical_name="Estradiol",
        loinc="2243-4",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Estradiol", "E2", "Estradiol Ultrasensitive",
                 "17-beta Estradiol",
                 "Estradiol (E2) [Mass/volume] in Serum or Plasma"),
    ),
    "lh": BiomarkerDefinition(
        biomarker_id="lh",
        canonical_name="Luteinizing Hormone",
        loinc="10501-5",
        normalized_unit="mIU/mL",
        allowed_specimens=_BLOOD,
        aliases=("LH", "Luteinizing Hormone",
                 "Lutropin [Units/volume] in Serum or Plasma"),
    ),
    "fsh": BiomarkerDefinition(
        biomarker_id="fsh",
        canonical_name="FSH",
        loinc="15067-2",
        normalized_unit="mIU/mL",
        allowed_specimens=_BLOOD,
        aliases=("FSH", "Follicle Stimulating Hormone", "Follitropin",
                 "Follitropin [Units/volume] in Serum or Plasma"),
    ),
    "homocysteine": BiomarkerDefinition(
        biomarker_id="homocysteine",
        canonical_name="Homocysteine",
        loinc="13965-9",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("Homocysteine", "Hcy", "Total Homocysteine",
                 "Homocysteine [Moles/volume] in Serum or Plasma"),
    ),
    "insulin": BiomarkerDefinition(
        biomarker_id="insulin",
        canonical_name="Insulin",
        loinc="20448-7",
        normalized_unit="uIU/mL",
        allowed_specimens=_BLOOD,
        aliases=("Insulin", "Insulin Fasting", "Fasting Insulin", "Serum Insulin",
                 "Insulin [Units/volume] in Serum or Plasma"),
    ),
    "tibc": BiomarkerDefinition(
        biomarker_id="tibc",
        canonical_name="Total Iron Binding Capacity",
        loinc="2500-7",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("TIBC", "Total Iron Binding Capacity", "Iron Binding Capacity",
                 "Iron Binding Capacity, Total",
                 "Iron binding capacity [Mass/volume] in Serum or Plasma"),
    ),
    "transferrin_saturation": BiomarkerDefinition(
        biomarker_id="transferrin_saturation",
        canonical_name="Transferrin Saturation",
        loinc="2502-3",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("Transferrin Saturation", "TSAT", "Iron Saturation", "Fe/TIBC Ratio", "Transferrin Sat",
                 "Iron saturation [Mass Fraction] in Serum or Plasma"),
    ),
    "lpa": BiomarkerDefinition(
        biomarker_id="lpa",
        canonical_name="Lipoprotein(a)",
        loinc="10835-7",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Lp(a)", "Lipoprotein a", "LPA",
                 "Lipoprotein a [Mass/volume] in Serum or Plasma"),
    ),
    "chol_hdl_ratio": BiomarkerDefinition(
        biomarker_id="chol_hdl_ratio",
        canonical_name="Total Cholesterol/HDL Ratio",
        loinc="9830-1",
        normalized_unit="ratio",
        allowed_specimens=_BLOOD,
        aliases=("Total Cholesterol/HDL Ratio", "Chol/HDL Ratio", "TC/HDL Ratio",
                 "Cholesterol Ratio (Total/HDL)", "Cholesterol Ratio",
                 "T. Chol/HDL Ratio",
                 "Cholesterol.total/Cholesterol in HDL [Mass Ratio] in Serum or Plasma"),
    ),
    "non_hdl_cholesterol": BiomarkerDefinition(
        biomarker_id="non_hdl_cholesterol",
        canonical_name="Non-HDL Cholesterol",
        loinc="43396-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Non-HDL Cholesterol", "Non-HDL Chol",
                 "Cholesterol non HDL [Mass/volume] in Serum or Plasma"),
    ),
    "psa": BiomarkerDefinition(
        biomarker_id="psa",
        canonical_name="PSA",
        loinc="2857-1",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("PSA", "PSA Total", "Prostate Specific Antigen",
                 "Prostate specific Ag [Mass/volume] in Serum or Plasma"),
    ),
    "testosterone_total": BiomarkerDefinition(
        biomarker_id="testosterone_total",
        canonical_name="Testosterone, Total",
        loinc="2986-8",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Testosterone", "Testosterone Total", "Total Testosterone",
                 "Testosterone,Total,MS",
                 "Testosterone, Total, LC/MS/MS",
                 "Testosterone [Mass/volume] in Serum or Plasma"),
    ),
    "shbg": BiomarkerDefinition(
        biomarker_id="shbg",
        canonical_name="SHBG",
        loinc="13967-5",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("SHBG", "Sex Hormone Binding Globulin",
                 "Sex hormone binding globulin [Moles/volume] in Serum or Plasma"),
    ),
    "free_testosterone": BiomarkerDefinition(
        biomarker_id="free_testosterone",
        canonical_name="Free Testosterone",
        loinc="2991-8",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Free Testosterone", "Testosterone Free",
                 "Free Testosterone(Direct)",
                 "Testosterone Free [Mass/volume] in Serum or Plasma"),
    ),
    "bioavailable_testosterone": BiomarkerDefinition(
        biomarker_id="bioavailable_testosterone",
        canonical_name="Bioavailable Testosterone",
        loinc="49041-7",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Bioavailable Testosterone", "Testosterone Bioavailable",
                 "Testosterone.bioavailable [Mass/volume] in Serum or Plasma"),
    ),
    # --- Urinalysis expansion ---
    "urine_blood": BiomarkerDefinition(
        biomarker_id="urine_blood",
        canonical_name="Urine Blood",
        loinc="5794-3",
        normalized_unit="",
        allowed_specimens=_URINE,
        aliases=("Urine Blood", "Blood, Urine", "Urine Blood Occult", "Occult Blood",
                 "Hemoglobin [Presence] in Urine by Test strip"),
    ),
    "urine_nitrite": BiomarkerDefinition(
        biomarker_id="urine_nitrite",
        canonical_name="Urine Nitrite",
        loinc="5802-4",
        normalized_unit="",
        allowed_specimens=_URINE,
        aliases=("Urine Nitrite", "Nitrite", "Nitrite, Urine",
                 "Nitrite [Presence] in Urine by Test strip"),
    ),
    "urine_leukocyte_esterase": BiomarkerDefinition(
        biomarker_id="urine_leukocyte_esterase",
        canonical_name="Urine Leukocyte Esterase",
        loinc="5799-2",
        normalized_unit="",
        allowed_specimens=_URINE,
        aliases=("Leukocyte Esterase", "Urine Leukocyte Esterase", "LE",
                 "Leukocyte esterase [Presence] in Urine by Test strip"),
    ),
    "urobilinogen": BiomarkerDefinition(
        biomarker_id="urobilinogen",
        canonical_name="Urine Urobilinogen",
        loinc="20405-7",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Urobilinogen", "Urine Urobilinogen",
                 "Urobilinogen [Mass/volume] in Urine by Test strip"),
    ),
    "urine_rbc": BiomarkerDefinition(
        biomarker_id="urine_rbc",
        canonical_name="Urine RBC",
        loinc="30391-7",
        normalized_unit="#/uL",
        allowed_specimens=_URINE,
        aliases=("RBC", "Urine RBC", "RBC, Urine", "Red Blood Cells, Urine",
                 "Erythrocytes [#/volume] in Urine by Automated count"),
    ),
    "urine_wbc": BiomarkerDefinition(
        biomarker_id="urine_wbc",
        canonical_name="Urine WBC",
        loinc="5821-4",
        normalized_unit="#/uL",
        allowed_specimens=_URINE,
        aliases=("WBC", "Urine WBC", "WBC, Urine", "White Blood Cells, Urine",
                 "Leukocytes [#/volume] in Urine by Automated count"),
    ),
    "epithelial_cells_urine": BiomarkerDefinition(
        biomarker_id="epithelial_cells_urine",
        canonical_name="Urine Epithelial Cells",
        loinc="5787-7",
        normalized_unit="#/hpf",
        allowed_specimens=_URINE,
        aliases=("Epithelial Cells", "Urine Epithelial Cells",
                 "Epithelial cells [#/area] in Urine sediment by Microscopy high power field"),
    ),
    "hyaline_casts": BiomarkerDefinition(
        biomarker_id="hyaline_casts",
        canonical_name="Hyaline Casts",
        loinc="5796-8",
        normalized_unit="#/lpf",
        allowed_specimens=_URINE,
        aliases=("Hyaline Casts", "Urine Hyaline Casts",
                 "Hyaline casts [#/area] in Urine sediment by Microscopy low power field"),
    ),
    "haptoglobin": BiomarkerDefinition(
        biomarker_id="haptoglobin",
        canonical_name="Haptoglobin",
        loinc="4542-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Haptoglobin", "Hapto",
                 "Haptoglobin [Mass/volume] in Serum or Plasma"),
    ),
    "transferrin": BiomarkerDefinition(
        biomarker_id="transferrin",
        canonical_name="Transferrin",
        loinc="3034-6",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Transferrin", "Serum Transferrin",
                 "Transferrin [Mass/volume] in Serum or Plasma"),
    ),
    # --- Wave 9: Clinical depth expansion ---
    "indirect_bilirubin": BiomarkerDefinition(
        biomarker_id="indirect_bilirubin",
        canonical_name="Indirect Bilirubin",
        loinc="1971-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Indirect Bilirubin", "Bilirubin, Indirect", "Unconjugated Bilirubin",
                 "Indirect Bili",
                 "Bilirubin.indirect [Mass/volume] in Serum or Plasma"),
    ),
    "cortisol": BiomarkerDefinition(
        biomarker_id="cortisol",
        canonical_name="Cortisol",
        loinc="2143-6",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Cortisol", "Serum Cortisol", "Cortisol AM",
                 "Cortisol, Total",
                 "Cortisol [Mass/volume] in Serum or Plasma"),
    ),
    "esr": BiomarkerDefinition(
        biomarker_id="esr",
        canonical_name="Erythrocyte Sedimentation Rate",
        loinc="4537-7",
        normalized_unit="mm/hr",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("ESR", "Sed Rate", "Sedimentation Rate", "Erythrocyte Sedimentation Rate",
                 "ESR Westergren", "Westergren ESR",
                 "Erythrocyte sedimentation rate by Westergren method"),
    ),
    "osmolality_serum": BiomarkerDefinition(
        biomarker_id="osmolality_serum",
        canonical_name="Osmolality, Serum",
        loinc="2692-2",
        normalized_unit="mOsm/kg",
        allowed_specimens=_BLOOD,
        aliases=("Osmolality", "Osmolality, Measured", "Serum Osmolality",
                 "Osmolality of Serum or Plasma"),
    ),
    "albumin_urine": BiomarkerDefinition(
        biomarker_id="albumin_urine",
        canonical_name="Urine Albumin",
        loinc="1754-1",
        normalized_unit="mg/L",
        allowed_specimens=_URINE,
        aliases=("Albumin, Urine", "Urine Albumin", "Microalbumin", "Urine Microalbumin",
                 "Albumin [Mass/volume] in Urine"),
    ),
    "albumin_creatinine_ratio": BiomarkerDefinition(
        biomarker_id="albumin_creatinine_ratio",
        canonical_name="Albumin/Creatinine Ratio, Urine",
        loinc="9318-7",
        normalized_unit="mg/g",
        allowed_specimens=_URINE,
        aliases=("Albumin/Creatinine, Urine", "Albumin/Creatinine Ratio", "ACR",
                 "Urine Albumin/Creatinine Ratio", "Microalbumin/Creatinine",
                 "Microalbumin/Creatinine [Mass Ratio] in Urine"),
    ),
    "total_protein_urine": BiomarkerDefinition(
        biomarker_id="total_protein_urine",
        canonical_name="Urine Total Protein",
        loinc="2036-2",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Total Protein, Urine", "Urine Total Protein", "Protein, Urine, Total",
                 "Protein [Mass/volume] in Urine"),
    ),
    "iga": BiomarkerDefinition(
        biomarker_id="iga",
        canonical_name="Immunoglobulin A",
        loinc="2458-8",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("IgA", "Immunoglobulin A",
                 "IgA [Mass/volume] in Serum or Plasma"),
    ),
    "igg": BiomarkerDefinition(
        biomarker_id="igg",
        canonical_name="Immunoglobulin G",
        loinc="2465-3",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("IgG", "Immunoglobulin G",
                 "IgG [Mass/volume] in Serum or Plasma"),
    ),
    "igm": BiomarkerDefinition(
        biomarker_id="igm",
        canonical_name="Immunoglobulin M",
        loinc="2472-9",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("IgM", "Immunoglobulin M",
                 "IgM [Mass/volume] in Serum or Plasma"),
    ),
    "reticulocyte_absolute": BiomarkerDefinition(
        biomarker_id="reticulocyte_absolute",
        canonical_name="Reticulocyte Count, Absolute",
        loinc="14196-0",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Reticulocyte Count, Absolute", "Absolute Reticulocyte Count",
                 "Reticulocytes [#/volume] in Blood"),
    ),
    # --- Wave 10: ICU hematology + urine chemistry + endocrine depth ---
    "bands": BiomarkerDefinition(
        biomarker_id="bands",
        canonical_name="Bands",
        loinc="26507-4",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Bands", "Band Cells", "Band Neutrophils",
                 "Band form neutrophils [#/volume] in Blood"),
    ),
    "bands_pct": BiomarkerDefinition(
        biomarker_id="bands_pct",
        canonical_name="Bands %",
        loinc="26508-2",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Bands", "Bands Percent", "Band Cells", "Band Cells Percent",
                 "Band Neutrophils", "Band Neutrophils Percent",
                 "Band form neutrophils/Leukocytes in Blood"),
    ),
    "immature_granulocytes": BiomarkerDefinition(
        biomarker_id="immature_granulocytes",
        canonical_name="Immature Granulocytes",
        loinc="53115-2",
        normalized_unit="K/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Immature Granulocytes", "IG", "Immature Grans",
                 "Immature granulocytes [#/volume] in Blood"),
    ),
    "immature_granulocytes_pct": BiomarkerDefinition(
        biomarker_id="immature_granulocytes_pct",
        canonical_name="Immature Granulocytes %",
        loinc="71695-1",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Immature Granulocytes Percent", "IG Percent",
                 "Immature Grans Percent",
                 "Immature Granulocytes/100 leukocytes"),
    ),
    "nrbc": BiomarkerDefinition(
        biomarker_id="nrbc",
        canonical_name="Nucleated Red Blood Cells",
        loinc="30392-5",
        normalized_unit="#/uL",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Nucleated Red Cells", "NRBC", "Nucleated RBC",
                 "Nucleated erythrocytes [#/volume] in Blood"),
    ),
    "nrbc_pct": BiomarkerDefinition(
        biomarker_id="nrbc_pct",
        canonical_name="Nucleated Red Blood Cells %",
        loinc="19048-8",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Nucleated Red Cells", "Nucleated Red Cells Percent",
                 "NRBC", "NRBC Percent", "Nucleated RBC", "Nucleated RBC Percent",
                 "Nucleated erythrocytes/Leukocytes [Ratio] in Blood"),
    ),
    "osmolality_urine": BiomarkerDefinition(
        biomarker_id="osmolality_urine",
        canonical_name="Osmolality, Urine",
        loinc="2695-5",
        normalized_unit="mOsm/kg",
        allowed_specimens=_URINE,
        aliases=("Osmolality, Urine", "Urine Osmolality", "Urinary Osmolality",
                 "Osmolality of Urine"),
    ),
    "sodium_urine": BiomarkerDefinition(
        biomarker_id="sodium_urine",
        canonical_name="Sodium, Urine",
        loinc="2955-3",
        normalized_unit="mEq/L",
        allowed_specimens=_URINE,
        aliases=("Sodium, Urine", "Urine Sodium", "Urinary Sodium", "Na, Urine"),
    ),
    "potassium_urine": BiomarkerDefinition(
        biomarker_id="potassium_urine",
        canonical_name="Potassium, Urine",
        loinc="2828-2",
        normalized_unit="mEq/L",
        allowed_specimens=_URINE,
        aliases=("Potassium, Urine", "Urine Potassium", "K, Urine"),
    ),
    "chloride_urine": BiomarkerDefinition(
        biomarker_id="chloride_urine",
        canonical_name="Chloride, Urine",
        loinc="2078-4",
        normalized_unit="mEq/L",
        allowed_specimens=_URINE,
        aliases=("Chloride, Urine", "Urine Chloride", "Cl, Urine"),
    ),
    "bun_urine": BiomarkerDefinition(
        biomarker_id="bun_urine",
        canonical_name="Urea Nitrogen, Urine",
        loinc="3095-7",
        normalized_unit="mg/dL",
        allowed_specimens=_URINE,
        aliases=("Urea Nitrogen, Urine", "BUN, Urine", "Urine BUN"),
    ),
    "pth": BiomarkerDefinition(
        biomarker_id="pth",
        canonical_name="Parathyroid Hormone",
        loinc="2731-8",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Parathyroid Hormone", "PTH", "Intact PTH", "PTH, Intact",
                 "Parathyrin.intact [Mass/volume] in Serum or Plasma"),
    ),
    "t3_total": BiomarkerDefinition(
        biomarker_id="t3_total",
        canonical_name="T3, Total",
        loinc="3053-6",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Triiodothyronine (T3)", "T3", "Total T3", "T3, Total",
                 "Triiodothyronine (T3), Total",
                 "Triiodothyronine (T3) [Mass/volume] in Serum or Plasma"),
    ),
    "t4_total": BiomarkerDefinition(
        biomarker_id="t4_total",
        canonical_name="T4, Total",
        loinc="3026-2",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Thyroxine (T4)", "T4", "Total T4", "T4, Total",
                 "Thyroxine (T4), Total",
                 "Thyroxine (T4) [Mass/volume] in Serum or Plasma"),
    ),
    "complement_c3": BiomarkerDefinition(
        biomarker_id="complement_c3",
        canonical_name="Complement C3",
        loinc="4485-9",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("C3", "Complement C3",
                 "Complement C3 [Mass/volume] in Serum or Plasma"),
    ),
    "complement_c4": BiomarkerDefinition(
        biomarker_id="complement_c4",
        canonical_name="Complement C4",
        loinc="4498-2",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("C4", "Complement C4",
                 "Complement C4 [Mass/volume] in Serum or Plasma"),
    ),
    "ammonia": BiomarkerDefinition(
        biomarker_id="ammonia",
        canonical_name="Ammonia",
        loinc="1842-4",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("Ammonia", "NH3", "Blood Ammonia",
                 "Ammonia [Moles/volume] in Plasma"),
    ),
    # --- Wave 11: Longevity-essential biomarkers ---
    "igf1": BiomarkerDefinition(
        biomarker_id="igf1",
        canonical_name="IGF-1",
        loinc="2484-4",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("IGF-1", "IGF1", "Insulin-like Growth Factor 1", "Somatomedin C",
                 "IGF I, LC/MS", "Insulin-Like Growth Factor I",
                 "Insulin-like growth factor-I [Mass/volume] in Serum or Plasma"),
    ),
    "cystatin_c": BiomarkerDefinition(
        biomarker_id="cystatin_c",
        canonical_name="Cystatin C",
        loinc="33863-2",
        normalized_unit="mg/L",
        allowed_specimens=_BLOOD,
        aliases=("Cystatin C", "Cys C",
                 "Cystatin C [Mass/volume] in Serum or Plasma"),
    ),
    "free_t3": BiomarkerDefinition(
        biomarker_id="free_t3",
        canonical_name="Free T3",
        loinc="3051-0",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Free T3", "FT3", "Triiodothyronine Free", "Free Triiodothyronine",
                 "Triiodothyronine (T3), Free",
                 "Triiodothyronine Free (T3) [Mass/volume] in Serum or Plasma"),
    ),
    "reverse_t3": BiomarkerDefinition(
        biomarker_id="reverse_t3",
        canonical_name="Reverse T3",
        loinc="3052-8",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Reverse T3", "rT3", "Reverse Triiodothyronine",
                 "Triiodothyronine reverse [Mass/volume] in Serum or Plasma"),
    ),
    "tpo_antibodies": BiomarkerDefinition(
        biomarker_id="tpo_antibodies",
        canonical_name="TPO Antibodies",
        loinc="8099-4",
        normalized_unit="IU/mL",
        allowed_specimens=_BLOOD,
        aliases=("TPO Antibodies", "Thyroid Peroxidase Antibodies", "Anti-TPO",
                 "TPO Ab", "Thyroid Peroxidase Ab",
                 "Thyroperoxidase Ab [Units/volume] in Serum or Plasma"),
    ),
    "thyroglobulin_antibodies": BiomarkerDefinition(
        biomarker_id="thyroglobulin_antibodies",
        canonical_name="Thyroglobulin Antibodies",
        loinc="8098-6",
        normalized_unit="IU/mL",
        allowed_specimens=_BLOOD,
        aliases=("Thyroglobulin Antibodies", "Anti-Thyroglobulin", "TgAb", "Anti-Tg",
                 "Thyroglobulin Ab [Units/volume] in Serum or Plasma"),
    ),
    "apoa1": BiomarkerDefinition(
        biomarker_id="apoa1",
        canonical_name="Apolipoprotein A-1",
        loinc="1869-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("ApoA1", "ApoA-1", "Apolipoprotein A-1", "Apolipoprotein A1", "Apo A1",
                 "Apolipoprotein A1 [Mass/volume] in Serum or Plasma"),
    ),
    "progesterone": BiomarkerDefinition(
        biomarker_id="progesterone",
        canonical_name="Progesterone",
        loinc="2839-9",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Progesterone", "P4", "Serum Progesterone",
                 "Progesterone [Mass/volume] in Serum or Plasma"),
    ),
    "amh": BiomarkerDefinition(
        biomarker_id="amh",
        canonical_name="Anti-Mullerian Hormone",
        loinc="58540-6",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("AMH", "Anti-Mullerian Hormone", "Anti-Mullerian", "Mullerian Inhibiting Substance",
                 "Mullerian-inhibiting substance [Mass/volume] in Serum or Plasma"),
    ),
    "vitamin_a": BiomarkerDefinition(
        biomarker_id="vitamin_a",
        canonical_name="Vitamin A",
        loinc="2923-1",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Vitamin A", "Retinol", "Serum Retinol",
                 "Retinol [Mass/volume] in Serum or Plasma"),
    ),
    "vitamin_c": BiomarkerDefinition(
        biomarker_id="vitamin_c",
        canonical_name="Vitamin C",
        loinc="2925-6",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Vitamin C", "Ascorbic Acid", "Ascorbate",
                 "Ascorbate [Mass/volume] in Serum or Plasma"),
    ),
    "vitamin_e": BiomarkerDefinition(
        biomarker_id="vitamin_e",
        canonical_name="Vitamin E",
        loinc="2927-2",
        normalized_unit="mg/L",
        allowed_specimens=_BLOOD,
        aliases=("Vitamin E", "Alpha-Tocopherol", "Tocopherol",
                 "alpha-Tocopherol [Mass/volume] in Serum or Plasma"),
    ),
    "zinc": BiomarkerDefinition(
        biomarker_id="zinc",
        canonical_name="Zinc",
        loinc="2601-3",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Zinc", "Zn", "Serum Zinc",
                 "Zinc [Mass/volume] in Serum or Plasma"),
    ),
    "selenium": BiomarkerDefinition(
        biomarker_id="selenium",
        canonical_name="Selenium",
        loinc="2820-9",
        normalized_unit="ug/L",
        allowed_specimens=_BLOOD,
        aliases=("Selenium", "Se", "Serum Selenium",
                 "Selenium [Mass/volume] in Serum or Plasma"),
    ),
    "copper": BiomarkerDefinition(
        biomarker_id="copper",
        canonical_name="Copper",
        loinc="2508-0",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Copper", "Cu", "Serum Copper",
                 "Copper [Mass/volume] in Serum or Plasma"),
    ),
    "fructosamine": BiomarkerDefinition(
        biomarker_id="fructosamine",
        canonical_name="Fructosamine",
        loinc="4983-3",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("Fructosamine", "Glycated Albumin", "Glycated Serum Protein",
                 "Fructosamine [Moles/volume] in Serum or Plasma"),
    ),
    "vldl_cholesterol": BiomarkerDefinition(
        biomarker_id="vldl_cholesterol",
        canonical_name="VLDL Cholesterol",
        loinc="2091-7",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("VLDL Cholesterol", "VLDL-C", "VLDL",
                 "VLDL Cholesterol Cal", "VLDL Cholesterol Calc",
                 "Cholesterol in VLDL [Mass/volume] in Serum or Plasma"),
    ),
    # --- Heavy metals / toxicology ---
    "mercury": BiomarkerDefinition(
        biomarker_id="mercury",
        canonical_name="Mercury",
        loinc="5677-0",
        normalized_unit="ug/L",
        allowed_specimens=_BLOOD,
        aliases=("Mercury", "Hg", "Mercury, Blood", "Mercury, Whole Blood",
                 "Mercury [Mass/volume] in Blood"),
    ),
    "lead": BiomarkerDefinition(
        biomarker_id="lead",
        canonical_name="Lead",
        loinc="5671-3",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Lead", "Pb", "Lead, Blood", "Lead Level",
                 "Lead [Mass/volume] in Blood"),
    ),
    "arsenic": BiomarkerDefinition(
        biomarker_id="arsenic",
        canonical_name="Arsenic",
        loinc="5580-6",
        normalized_unit="ug/L",
        allowed_specimens=_BLOOD,
        aliases=("Arsenic", "As", "Arsenic, Blood",
                 "Arsenic [Mass/volume] in Blood"),
    ),
    "manganese": BiomarkerDefinition(
        biomarker_id="manganese",
        canonical_name="Manganese",
        loinc="32551-4",
        normalized_unit="ug/L",
        allowed_specimens=_BLOOD,
        aliases=("Manganese", "Mn", "Manganese, Blood",
                 "Manganese [Mass/volume] in Blood"),
    ),
    "cadmium": BiomarkerDefinition(
        biomarker_id="cadmium",
        canonical_name="Cadmium",
        loinc="5611-9",
        normalized_unit="ug/L",
        allowed_specimens=_BLOOD,
        aliases=("Cadmium", "Cd", "Cadmium, Blood",
                 "Cadmium [Mass/volume] in Blood"),
    ),
    # --- Wave 12: Advanced longevity (Tier 1 from market research) ---
    "ldl_particle_number": BiomarkerDefinition(
        biomarker_id="ldl_particle_number",
        canonical_name="LDL Particle Number",
        loinc="54434-6",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("LDL Particle Number", "LDL-P", "LDL Particle Count",
                 "Low density lipoprotein particle number [#/volume] in Serum or Plasma by NMR"),
    ),
    "small_dense_ldl": BiomarkerDefinition(
        biomarker_id="small_dense_ldl",
        canonical_name="Small Dense LDL",
        loinc="90364-1",
        normalized_unit="mg/dL",
        allowed_specimens=_BLOOD,
        aliases=("Small Dense LDL", "sdLDL", "sdLDL-C", "Small Dense LDL Cholesterol"),
    ),
    "oxidized_ldl": BiomarkerDefinition(
        biomarker_id="oxidized_ldl",
        canonical_name="Oxidized LDL",
        loinc="68935-6",
        normalized_unit="U/L",
        allowed_specimens=_BLOOD,
        aliases=("Oxidized LDL", "OxLDL", "Ox-LDL"),
    ),
    "lp_pla2": BiomarkerDefinition(
        biomarker_id="lp_pla2",
        canonical_name="Lp-PLA2",
        loinc="86951-1",
        normalized_unit="nmol/min/mL",
        allowed_specimens=_BLOOD,
        aliases=("Lp-PLA2", "PLAC", "Lipoprotein-associated Phospholipase A2",
                 "Phospholipase A2 group 7 [Enzymatic activity/volume] in Serum or Plasma"),
    ),
    "il6": BiomarkerDefinition(
        biomarker_id="il6",
        canonical_name="Interleukin-6",
        loinc="26881-3",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("IL-6", "Interleukin 6",
                 "Interleukin 6 [Mass/volume] in Serum or Plasma"),
    ),
    "tnf_alpha": BiomarkerDefinition(
        biomarker_id="tnf_alpha",
        canonical_name="TNF-alpha",
        loinc="3074-2",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("TNF-alpha", "Tumor Necrosis Factor alpha",
                 "Tumor necrosis factor alpha [Mass/volume] in Serum or Plasma"),
    ),
    "leptin": BiomarkerDefinition(
        biomarker_id="leptin",
        canonical_name="Leptin",
        loinc="21365-2",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Leptin", "Serum Leptin",
                 "Leptin [Mass/volume] in Serum or Plasma"),
    ),
    "c_peptide": BiomarkerDefinition(
        biomarker_id="c_peptide",
        canonical_name="C-Peptide",
        loinc="1986-9",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("C-Peptide", "Connecting Peptide",
                 "C peptide [Mass/volume] in Serum or Plasma"),
    ),
    "prolactin": BiomarkerDefinition(
        biomarker_id="prolactin",
        canonical_name="Prolactin",
        loinc="2842-3",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Prolactin", "PRL",
                 "Prolactin [Mass/volume] in Serum or Plasma"),
    ),
    "free_psa": BiomarkerDefinition(
        biomarker_id="free_psa",
        canonical_name="Free PSA",
        loinc="10886-0",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("Free PSA", "PSA Free ng/mL",
                 "Prostate specific Ag Free [Mass/volume] in Serum or Plasma"),
    ),
    "psa_free_pct": BiomarkerDefinition(
        biomarker_id="psa_free_pct",
        canonical_name="PSA % Free",
        loinc="12841-3",
        normalized_unit="%",
        allowed_specimens=_BLOOD,
        aliases=("PSA % Free", "PSA Free Percent", "Free PSA Percent", "Percent Free PSA",
                 "Prostate specific Ag Free/Prostate specific Ag.total in Serum or Plasma"),
    ),
    "rheumatoid_factor": BiomarkerDefinition(
        biomarker_id="rheumatoid_factor",
        canonical_name="Rheumatoid Factor",
        loinc="11572-5",
        normalized_unit="IU/mL",
        allowed_specimens=_BLOOD,
        aliases=("Rheumatoid Factor", "RF", "RA Factor",
                 "Rheumatoid factor [Units/volume] in Serum or Plasma"),
    ),
    "ana_screen": BiomarkerDefinition(
        biomarker_id="ana_screen",
        canonical_name="ANA Screen",
        loinc="8061-4",
        normalized_unit="",
        allowed_specimens=_BLOOD,
        aliases=("ANA", "ANA Screen", "Antinuclear Antibody", "Antinuclear Antibodies",
                 "Nuclear Ab [Units/volume] in Serum"),
    ),
    "methylmalonic_acid": BiomarkerDefinition(
        biomarker_id="methylmalonic_acid",
        canonical_name="Methylmalonic Acid",
        loinc="13964-2",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Methylmalonic Acid", "MMA",
                 "Methylmalonate [Moles/volume] in Serum or Plasma"),
    ),
    "adiponectin": BiomarkerDefinition(
        biomarker_id="adiponectin",
        canonical_name="Adiponectin",
        loinc="47828-9",
        normalized_unit="ug/mL",
        allowed_specimens=_BLOOD,
        aliases=("Adiponectin", "Adiponectin, Serum",
                 "Adiponectin [Mass/volume] in Serum or Plasma"),
    ),
    "tmao": BiomarkerDefinition(
        biomarker_id="tmao",
        canonical_name="TMAO",
        loinc="90360-9",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("TMAO", "Trimethylamine N-oxide",
                 "Trimethylamine N-oxide [Moles/volume] in Serum or Plasma"),
    ),
    "gdf15": BiomarkerDefinition(
        biomarker_id="gdf15",
        canonical_name="GDF-15",
        loinc="92665-9",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("GDF-15", "GDF15", "Growth Differentiation Factor 15",
                 "Growth differentiation factor 15 [Mass/volume] in Serum or Plasma"),
    ),
    "dht": BiomarkerDefinition(
        biomarker_id="dht",
        canonical_name="Dihydrotestosterone",
        loinc="1848-1",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("DHT", "Dihydrotestosterone", "5-alpha-DHT",
                 "Dihydrotestosterone [Mass/volume] in Serum or Plasma"),
    ),
    "omega3_index": BiomarkerDefinition(
        biomarker_id="omega3_index",
        canonical_name="Omega-3 Index",
        loinc="88998-0",
        normalized_unit="%",
        allowed_specimens=_WHOLE_BLOOD,
        aliases=("Omega-3 Index", "EPA+DHA Index",
                 "Eicosapentaenoic+Docosahexaenoic acid/Total fatty acids in Red Blood Cells"),
    ),
    "ige_total": BiomarkerDefinition(
        biomarker_id="ige_total",
        canonical_name="Total IgE",
        loinc="19113-0",
        normalized_unit="IU/mL",
        allowed_specimens=_BLOOD,
        aliases=("IgE", "Total IgE", "Immunoglobulin E",
                 "IgE [Units/volume] in Serum or Plasma"),
    ),
    # --- Wave 13: Niche longevity + specialty ---
    "acth": BiomarkerDefinition(
        biomarker_id="acth",
        canonical_name="ACTH",
        loinc="2141-0",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("ACTH", "Adrenocorticotropic Hormone", "Corticotropin"),
    ),
    "pregnenolone": BiomarkerDefinition(
        biomarker_id="pregnenolone",
        canonical_name="Pregnenolone",
        loinc="2897-7",
        normalized_unit="ng/dL",
        allowed_specimens=_BLOOD,
        aliases=("Pregnenolone", "Pregnenolone, Serum", "Serum Pregnenolone",
                 "Pregnenolone [Mass/volume] in Serum or Plasma"),
    ),
    "glycomark": BiomarkerDefinition(
        biomarker_id="glycomark",
        canonical_name="1,5-Anhydroglucitol",
        loinc="53553-4",
        normalized_unit="ug/mL",
        allowed_specimens=_BLOOD,
        aliases=("GlycoMark", "1,5-AG", "1,5-Anhydroglucitol"),
    ),
    "coq10": BiomarkerDefinition(
        biomarker_id="coq10",
        canonical_name="Coenzyme Q10",
        loinc="46986-6",
        normalized_unit="ug/mL",
        allowed_specimens=_BLOOD,
        aliases=("CoQ10", "Coenzyme Q10", "Ubiquinone"),
    ),
    "estrone": BiomarkerDefinition(
        biomarker_id="estrone",
        canonical_name="Estrone",
        loinc="2015-6",
        normalized_unit="pg/mL",
        allowed_specimens=_BLOOD,
        aliases=("Estrone", "E1", "Estrone, Serum",
                 "Estrone [Mass/volume] in Serum or Plasma"),
    ),
    "cortisol_free": BiomarkerDefinition(
        biomarker_id="cortisol_free",
        canonical_name="Free Cortisol",
        loinc="9546-3",
        normalized_unit="ug/dL",
        allowed_specimens=_BLOOD,
        aliases=("Free Cortisol", "Cortisol Free",
                 "Cortisol [Mass/volume] in Serum or Plasma --free"),
    ),
    "igfbp3": BiomarkerDefinition(
        biomarker_id="igfbp3",
        canonical_name="IGFBP-3",
        loinc="2480-2",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("IGFBP-3", "IGF Binding Protein 3", "Insulin-like Growth Factor Binding Protein 3"),
    ),
    "anti_ccp": BiomarkerDefinition(
        biomarker_id="anti_ccp",
        canonical_name="Anti-CCP Antibodies",
        loinc="53027-9",
        normalized_unit="U/mL",
        allowed_specimens=_BLOOD,
        aliases=("Anti-CCP", "CCP Antibodies", "Cyclic Citrullinated Peptide Antibodies"),
    ),
    "beta2_microglobulin": BiomarkerDefinition(
        biomarker_id="beta2_microglobulin",
        canonical_name="Beta-2 Microglobulin",
        loinc="1952-1",
        normalized_unit="mg/L",
        allowed_specimens=_BLOOD,
        aliases=("Beta-2 Microglobulin", "B2M",
                 "Beta-2 Microglobulin [Mass/volume] in Serum or Plasma"),
    ),
    "ca125": BiomarkerDefinition(
        biomarker_id="ca125",
        canonical_name="CA-125",
        loinc="10334-1",
        normalized_unit="U/mL",
        allowed_specimens=_BLOOD,
        aliases=("CA-125", "Cancer Antigen 125",
                 "CA-125 [Units/volume] in Serum or Plasma"),
    ),
    "cea": BiomarkerDefinition(
        biomarker_id="cea",
        canonical_name="CEA",
        loinc="2039-6",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("CEA", "Carcinoembryonic Antigen", "Carcinoembyronic Antigen (CEA)"),
    ),
    "afp": BiomarkerDefinition(
        biomarker_id="afp",
        canonical_name="Alpha-Fetoprotein",
        loinc="1834-1",
        normalized_unit="ng/mL",
        allowed_specimens=_BLOOD,
        aliases=("AFP", "Alpha-Fetoprotein",
                 "Alpha-Fetoprotein [Mass/volume] in Serum or Plasma"),
    ),
    "ldl_particle_size": BiomarkerDefinition(
        biomarker_id="ldl_particle_size",
        canonical_name="LDL Particle Size",
        loinc="17782-4",
        normalized_unit="nm",
        allowed_specimens=_BLOOD,
        aliases=("LDL Particle Size", "LDL Peak Size", "LDL Size"),
    ),
    # --- NMR LipoProfile ---
    "small_ldl_particle": BiomarkerDefinition(
        biomarker_id="small_ldl_particle",
        canonical_name="Small LDL Particle Number",
        loinc="55440-2",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Small LDL-P", "Small LDL Particle Number", "Small LDL Particles"),
    ),
    "hdl_particle": BiomarkerDefinition(
        biomarker_id="hdl_particle",
        canonical_name="HDL Particle Number",
        loinc="55437-8",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("HDL-P", "HDL Particle Number", "Total HDL Particles",
                 "HDL Particle Number (NMR)"),
    ),
    "large_hdl_particle": BiomarkerDefinition(
        biomarker_id="large_hdl_particle",
        canonical_name="Large HDL Particle Number",
        loinc="55436-0",
        normalized_unit="umol/L",
        allowed_specimens=_BLOOD,
        aliases=("Large HDL-P", "Large HDL Particles", "Large HDL Particle Number"),
    ),
    "large_vldl_particle": BiomarkerDefinition(
        biomarker_id="large_vldl_particle",
        canonical_name="Large VLDL Particle Number",
        loinc="55438-6",
        normalized_unit="nmol/L",
        allowed_specimens=_BLOOD,
        aliases=("Large VLDL-P", "Large VLDL Particles", "Large VLDL Particle Number"),
    ),
    "lp_ir_score": BiomarkerDefinition(
        biomarker_id="lp_ir_score",
        canonical_name="Lipoprotein Insulin Resistance Score",
        loinc="86909-9",
        normalized_unit="",
        allowed_specimens=_BLOOD,
        aliases=("LP-IR", "LP-IR Score", "Lipoprotein Insulin Resistance Score",
                 "LP-IR Score (NMR)"),
    ),
}


ALIAS_INDEX: dict[str, list[str]] = {}
for biomarker_id, biomarker in BIOMARKER_CATALOG.items():
    for alias in biomarker.aliases:
        alias_key = normalize_key(alias)
        candidates = ALIAS_INDEX.setdefault(alias_key, [])
        if biomarker_id not in candidates:
            candidates.append(biomarker_id)


def load_custom_aliases(path: Path) -> int:
    """Load custom alias mappings from a JSON file and merge into ALIAS_INDEX.

    The JSON file should be a dict mapping biomarker_id to a list of alias strings:
    {
        "glucose_serum": ["Blood Sugar", "FBG", "Fasting Blood Sugar"],
        "hba1c": ["GHb", "Glycosylated Hemoglobin"]
    }

    Returns the number of aliases added.
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Custom alias file must be a JSON object mapping biomarker_id to alias lists.")
    added = 0
    for biomarker_id, aliases in data.items():
        if biomarker_id not in BIOMARKER_CATALOG:
            logger.warning("Custom alias file references unknown biomarker_id: %r (skipped)", biomarker_id)
            continue
        if not isinstance(aliases, list):
            continue
        for alias in aliases:
            if not isinstance(alias, str):
                continue
            alias_key = normalize_key(alias)
            candidates = ALIAS_INDEX.setdefault(alias_key, [])
            if biomarker_id not in candidates:
                candidates.append(biomarker_id)
                added += 1
    return added
